name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Запуск при пуше в основную ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Получаем код из репозитория

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Настроим поддержку Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coordinator-bot:latest
          no-cache: true

      - name: SSH to VPS and update container
        uses: appleboy/ssh-action@v0.1.6  # Подключаемся к серверу по SSH
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coordinator-bot:latest
            sudo docker cp coordinator-bot:/app/. /root/
            sudo docker stop coordinator-bot || true
            sudo docker rm coordinator-bot || true
            sudo docker run -d --name coordinator-bot --restart always \
              ${{ secrets.DOCKER_USERNAME }}/coordinator-bot:latest